### ISSUE TITLE
'fbs run' is not run

### ISSUE THREAD

**Issue by ishida722** [RUTILEA/SDTest#83]
Hi, I tried to run the SDTest.

```bash
pip install -r requirements.txt
fbs run
```

I got an error.

```
Traceback (most recent call last):
  File "C:\Project\SDTest\src\main\python\main.py", line 1, in <module>
    from fbs_runtime.application_context import ApplicationContext
ImportError: cannot import name 'ApplicationContext'
```

environment
- windows 10
- python 3.6.6
- commit: 140b7f4 - first commit (master branch)

**Comment by dryout** [comment]
Just to make sure, have you tried `pip install -r requirements/windows.txt -U`?

**Comment by dryout** [comment]
and `pip install -r requirements/base.txt -U`

**Comment by zoldaten** [comment]
try to use in main.py:
**from fbs_runtime.application_context.PyQt5 import ApplicationContext**
